import { NgModule } from '@angular/core';
import {
    MatSelectModule,
    MatDialogModule,
    MatSnackBarModule,
    MatGridListModule,
    MatDividerModule,
    MatCardModule,
    MatButtonModule,
    MatSidenavModule,
    MatCheckboxModule,
    MatToolbarModule,
    MatMenuModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatTooltipModule,
} from '@angular/material';

@NgModule({
    imports: [
        MatSelectModule,
        MatDialogModule,
        MatSnackBarModule,
        MatGridListModule,
        MatDividerModule,
        MatCardModule,
        MatButtonModule,
        MatSidenavModule,
        MatCheckboxModule,
        MatToolbarModule,
        MatMenuModule,
        MatIconModule,
        MatInputModule,
        MatListModule,
        MatTooltipModule,
    ],
    exports: [
        MatSelectModule,
        MatDialogModule,
        MatSnackBarModule,
        MatGridListModule,
        MatDividerModule,
        MatCardModule,
        MatButtonModule,
        MatSidenavModule,
        MatCheckboxModule,
        MatToolbarModule,
        MatMenuModule,
        MatIconModule,
        MatInputModule,
        MatListModule,
        MatTooltipModule,
    ]
})
export class MaterialModule { }
